# Publish docker/desktop-containerd-registry-mirror image as a tag is created
name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      -
        name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f  # v4.6.0
        env:
          DOCKERHUB_OIDC_CONNECTIONID: ${{ secrets.OIDC_ID_CONNECTION }}
          DOCKERHUB_OIDC_EXPIREIN: 3600
        with:
          username: docker
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Build and push image
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 --push --tag docker/desktop-cloud-provider-kind:${{ github.ref_name }} .
